/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as ExpertoIdRouteImport } from './routes/experto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertoIdRoute = ExpertoIdRouteImport.update({
  id: '/experto/$id',
  path: '/experto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmar': typeof ConfirmarRoute
  '/experto/$id': typeof ExpertoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmar': typeof ConfirmarRoute
  '/experto/$id': typeof ExpertoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmar': typeof ConfirmarRoute
  '/experto/$id': typeof ExpertoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirmar' | '/experto/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirmar' | '/experto/$id'
  id: '__root__' | '/' | '/confirmar' | '/experto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmarRoute: typeof ConfirmarRoute
  ExpertoIdRoute: typeof ExpertoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experto/$id': {
      id: '/experto/$id'
      path: '/experto/$id'
      fullPath: '/experto/$id'
      preLoaderRoute: typeof ExpertoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmarRoute: ConfirmarRoute,
  ExpertoIdRoute: ExpertoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
